# Generated by Django 5.1 on 2024-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='چت آی دی تلگرام'),
        ),
    ]
